### ISSUE TITLE
Explicitly clarify that test number is in DE in UI

### ISSUE THREAD

**Issue by Iiridayn** [RUB-SysSec/mobile_sentinel#1]
The app warned that there might be costs, but I didn't expect the call to Germany. It would be useful to state _where_ the test number is so the user can make an informed decision about the costs before starting the test.

**Comment by Iiridayn** [comment]
I did try to find the number in various places before placing the call (though not the source code). So, it might be sufficient just to list the default number somewhere.

**Comment by Abyss777** [comment]
Hello
It would be better even customize phone number to test. In settings or somewhere.

**Comment by davidrupprecht** [comment]
Thank you for your comments. We will clarify this soon. Under Settings you can change the Call Number.

**Comment by ValZapod** [comment]
Hahahahaha, you made my day guys! I recommend +800 9379 9642 or +800 3551 3551 (casinos)
+800, zone is, as you know, is free to call from every place on earth! (Yes, it is not +1800, it is international free https://en.wikipedia.org/wiki/Toll-free_telephone_number#Universal_International_Freephone_Service ).

**Comment by ValZapod** [comment]
BTW, I have a question guys. If you use Enhanced Voice Services with 20 kHz audio bandwidth are you safe? You cannot decode it unless you will use open decoder and encoder  https://github.com/youzzzwww/evs https://itectec.com/archive/3gpp-specification-ts-26-442/ but there is not packetisers in Wireshark, is not it?

**Comment by bedrankara** [comment]
The user is currently informed that there may be costs related with the test calls to the number. Further they are notified that a custom number may be chosen at the settings. In the next release I will add that the test number is located in Germany additionally.
