### ISSUE TITLE
Xiaomi Mi Mix 5G - App Crash

### ISSUE THREAD

**Issue by ggrocott** [RUB-SysSec/mobile_sentinel#10]
I have rooted the phone and installed the App. When I run the test, it gets 4 calls in to testing and the App crashes out. I have tried uninstalling and reinstalling again but same .

**Comment by bedrankara** [comment]
Hey,
which Android version is currently installed?
Further, do you get a prompt to grant root/superuser access once you install and start the app?

**Comment by ggrocott** [comment]
Hi Brendan,

I have managed to fix it. When I was going via the Root process, it didnt install the Magisk correctly and I needed Magisk Manager so that when I ran the MobileSentinel, it asked for SU permissions which was granted.

All good now and works.
