### ISSUE TITLE
Python syntax error in qualcommparser.py

### ISSUE THREAD

**Issue by cclauss** [RUB-SysSec/mobile_sentinel#4]
https://github.com/RUB-SysSec/mobile_sentinel/blob/master/app/src/main/python/parsers/qualcomm/qualcommparser.py#L281

[flake8](http://flake8.pycqa.org) testing of https://github.com/RUB-SysSec/mobile_sentinel on Python 3.6.10

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./app/src/main/python/iodevices/fileio.py:37:31: F821 undefined name 'write_buf'
            buf = util.unwrap(write_buf)
                              ^
./app/src/main/python/parsers/qualcomm/qualcommparser.py:281:5: F722 syntax error in forward annotation 'DIAG_LOG_F data without trailing CRC'
    def parse_diag_log(self, pkt: "DIAG_LOG_F data without trailing CRC", radio_id = 0):
    ^
./app/src/main/python/parsers/qualcomm/pycrate/pycrate_core/utils_py2.py:61:27: F821 undefined name 'long'
    integer_types = (int, long, _MPZ_T)
                          ^
./app/src/main/python/parsers/qualcomm/pycrate/pycrate_core/utils_py2.py:63:27: F821 undefined name 'long'
    integer_types = (int, long)
                          ^
./app/src/main/python/parsers/qualcomm/pycrate/pycrate_core/utils_py2.py:67:19: F821 undefined name 'unicode'
str_types = (str, unicode)
                  ^
1     F722 syntax error in forward annotation 'DIAG_LOG_F data without trailing CRC'
4     F821 undefined name 'write_buf'
5
```
https://flake8.pycqa.org/en/latest/user/error-codes.html

On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead, these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python, they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and equality in Python.  Use ==/!= to compare str, bytes, and int literals is the classic case.  These are areas where __a == b__ is True but __a is b__ is False (or vice versa).  Python >= 3.8 will raise SyntaxWarnings on these instances.
* F7 tests logic errors and syntax errors in type hints
* F82 tests are almost always _undefined names_ which are usually a sign of a typo, missing imports, or code that has not been ported to Python 3.  These also would be compile-time errors in a compiled language but in Python, a __NameError__ is raised which will halt/crash the script on the user.

**Comment by bedrankara** [comment]
Hello,
thank you for the testing. As the mentioned code is part of the SCAT tool and the PyCrate library I would suggest you to 
direct these issues to the corresponding repositories directly. 

https://github.com/P1sec/pycrate
https://github.com/fgsect/scat
