### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by dotlineX** [RUB-SysSec/mobile_sentinel#5]
The app crashes %10 thru the test

Android version 10

**Comment by bedrankara** [comment]
We are going to test some Android 10 models, however it is not supported yet.
Which phone model did you use?

**Comment by dotlineX** [comment]
I'm not sure. Tried on an friends oppo phone

**Comment by bedrankara** [comment]
If the app is bumped to a version where Android 10 support is included feel free to re-test, thank you.
