### ISSUE TITLE
No Issue [works also with OnePlus 8 Pro on Android 10]

### ISSUE THREAD

**Issue by darox** [RUB-SysSec/mobile_sentinel#6]
I can confirm that the app also works on OnePlus 8 Pro on Android 10.

**Comment by bedrankara** [comment]
Hey,

thank you very much for your testing.
Could you perhaps share some .qmdl log files generated by our app? (located in the MobileSentinel folder on your SDCard).
This helps us to verify that the essential functionality of our app work properly, as we are limited in the variety of devices we have.

**Comment by darox** [comment]
> Hey,
> 
> thank you very much for your testing.
> Could you perhaps share some .qmdl log files generated by our app? (located in the MobileSentinel folder on your SDCard).
> This helps us to verify that the essential functionality of our app work properly, as we are limited in the variety of devices we have.
> 
> 

Sure. Please share a mail address I can send it to.

**Comment by bedrankara** [comment]
> > Hey,
> > thank you very much for your testing.
> > Could you perhaps share some .qmdl log files generated by our app? (located in the MobileSentinel folder on your SDCard).
> > This helps us to verify that the essential functionality of our app work properly, as we are limited in the variety of devices we have.
> 
> Sure. Please share a mail address I can send it to.

Appreciated, drop a mail at bedran.karakoc@ruhr-uni-bochum.de

**Comment by bedrankara** [comment]
I checked the dumps and it looks like we do not get some of the necessary logs in Android 10.
We are investigating the root cause right now. 

Thanks for the report

**Comment by darox** [comment]
@bedrankara Thank you for the feedback. May you share your findings.
