### ISSUE TITLE
App fails on Pixel 3a XL

### ISSUE THREAD

**Issue by norman-shulman** [RUB-SysSec/mobile_sentinel#7]
Pixel 3a XL (Qualcomm Snapdragon 670 chip)
Android 10 in developer mode
VoLTE network
SIM card: LTE voice and data
MobileSentinel 1.0

App doesn't detect IMSI (ICCID on this phone) and shows isVolteEnabled: False.
Changed Call Number to this phone.
Starting detection makes 4 calls and then gives up without logging anything.

**Comment by bedrankara** [comment]
Hello, 

thanks for your report. The Pixel 3(a) devices do not currently expose the qualcomm diag driver which is required by the app.
Further Android 10 is currently not supported but we are working on it.
